from __future__ import annotations

from enum import Enum


class ExtractedValueType(str, Enum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    DECIMAL = "DECIMAL"
    DATE = "DATE"
    DATETIME = "DATETIME"
    BOOLEAN = "BOOLEAN"
    CURRENCY = "CURRENCY"
    PERCENTAGE = "PERCENTAGE"
    UNKNOWN = "UNKNOWN"


class ExtractionMethod(str, Enum):
    RULE_BASED = "RULE_BASED"
    MODEL_BASED = "MODEL_BASED"
    TEMPLATE_BASED = "TEMPLATE_BASED"
    MANUAL_ENTRY = "MANUAL_ENTRY"
    IMPORT = "IMPORT"


class FieldKey(str, Enum):
    POLICY_NUMBER = "POLICY_NUMBER"
    ACCOUNT_NUMBER = "ACCOUNT_NUMBER"
    REPORT_DATE = "REPORT_DATE"
    START_DATE = "START_DATE"
    END_DATE = "END_DATE"
    BALANCE = "BALANCE"
    EMPLOYEE_CONTRIBUTION = "EMPLOYEE_CONTRIBUTION"
    EMPLOYER_CONTRIBUTION = "EMPLOYER_CONTRIBUTION"
    WITHDRAWAL = "WITHDRAWAL"
    OUTSTANDING_BALANCE = "OUTSTANDING_BALANCE"
    INSTITUTION_NAME = "INSTITUTION_NAME"
    EMPLOYER_NAME = "EMPLOYER_NAME"
    SALARY_BASE = "SALARY_BASE"
    TOTAL_UNITS = "TOTAL_UNITS"
    OTHER = "OTHER"


__all__ = [
    "ExtractedValueType",
    "ExtractionMethod",
    "FieldKey",
]
